version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
platform:
  - x86
  - x64
  - ARM
  - ARM64  
configuration:
  - Debug
  - Release
build:
  project: Windows\corerundll.sln
  verbosity: detailed