version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
platform:
  - x86
  - x64
  - ARM
  - ARM64  
configuration:
  - Debug
  - Release
build:
  project: Windows\corerundll.sln
  verbosity: detailed
skip_commits:
  files:
    - '**/*.md'
- path: Windows\bin.X86\Release\corehook32.dll
  name: corehook-X86
- path: Windows\bin.X64\Release\corehook64.dll
  name: CoreHook-X64  
- path: Windows\bin.ARM\Release\corehook32.dll
  name: corehook-ARM
- path: Windows\bin.ARM64\Release\corehook64.dll
  name: corehook-ARM64