version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x86
  - x64
  - ARM
  - ARM64

configuration:
  - Debug
  - Release

before_build:
  - nuget restore build\msvc\coreload.sln

build:
  project: build\msvc\coreload.sln
  verbosity: detailed

skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
  
after_build:
  7z a coreload-%CONFIGURATION%-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\bin\%PLATFORM%\%CONFIGURATION%\coreload*.dll

artifacts:
- path: coreload-%CONFIGURATION%-%PLATFORM%.zip
  name: Releases

deploy:
  provider: GitHub
  description: "corehook host module"
  auth_token:
    secure: 99ssBJ/lNK6AL1FNajtOhloP5bXeUAm8m+cI0us6pW1hVw84MTKxwYzfurYMuaOQ
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true